apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "redis" "ctx" $) | nindent 4 }}
spec:
  selector:
    {{- include "parcelpigeon.selectorLabels" "redis" | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
