apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "web" "ctx" $) | nindent 4 }}
spec:
  selector:
    {{- include "parcelpigeon.selectorLabels" "web" | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
