apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-service-config
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "tracking-service" "ctx" $) | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
