apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "tracking-service" "ctx" $) | nindent 4 }}
spec:
  selector:
    {{- include "parcelpigeon.selectorLabels" "tracking-service" | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
