# Default values for the rabbitmq chart.

image:
  repository: rabbitmq
  tag: 3.13-management-alpine
replicas: 1
ports:
  amqp: 5672
  management: 15672
persistence:
  size: 1Gi
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi
