apiVersion: v1
kind: Secret
metadata:
  name: shipments-service-secret
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "shipments-service" "ctx" $) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
