# Default values for the tracking-service chart.

image:
  repository: ghcr.io/chnu-devops/tracking-service
  tag: latest
replicas: 1
port: 8002
config:
  TRACKING_HTTP_ADDR: ":8002"
  TRACKING_REDIS_ADDR: "redis:6379"
  TRACKING_EXCHANGE: "parcelpigeon"
  TRACKING_QUEUE: "tracking.projector"
  TRACKING_SHIPMENTS_URL: "http://shipments-service:8000"
  TRACKING_SMTP_ADDR: "mailhog:1025"
  TRACKING_MAIL_FROM: "no-reply@parcelpigeon.test"
  TRACKING_ENABLE_CONSUMER: "true"
secret:
  TRACKING_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
