# Default values for the postgres chart.

image:
  repository: postgres
  tag: 16-alpine
replicas: 1
port: 5432
persistence:
  size: 1Gi
secret:
  POSTGRES_USER: parcelpigeon
  POSTGRES_PASSWORD: parcelpigeon
  POSTGRES_DB: shipments
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi
