apiVersion: v2
name: gateway
description: ParcelPigeon gateway — public API reverse proxy
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: parcelpigeon-common
    version: 0.1.0
    repository: file://../../../lib/parcelpigeon-common
