apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "postgres" "ctx" $) | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "parcelpigeon.selectorLabels" "postgres" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "parcelpigeon.labels" (dict "name" "postgres" "ctx" $) | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.secret.POSTGRES_USER | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.secret.POSTGRES_USER | quote }}]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
