apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "parcelpigeon.labels" (dict "name" "postgres" "ctx" $) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
