apiVersion: v2
name: mailhog
description: ParcelPigeon MailHog — fake SMTP server for tracking emails
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: parcelpigeon-common
    version: 0.1.0
    repository: file://../../../lib/parcelpigeon-common
