# Default values for the mailhog chart.

image:
  repository: mailhog/mailhog
  tag: v1.0.1
replicas: 1
ports:
  smtp: 1025
  ui: 8025
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
