apiVersion: v2
name: redis
description: ParcelPigeon Redis — tracking read model
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: parcelpigeon-common
    version: 0.1.0
    repository: file://../../../lib/parcelpigeon-common
