# Default values for the redis chart.

image:
  repository: redis
  tag: 7-alpine
replicas: 1
port: 6379
persistence:
  size: 1Gi
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 256Mi
